### PR TITLE
File Error Handling

### PR DESCRIPTION
**Pull request by KennethSkylight**
# PULL REQUEST

## Summary

Adds error handling for both .zip and too large file size. It doesn't use the default React USWDS because it was too difficult. Error handling is all custom. Includes the tests for the functionality as well

### Large file error
image

### Wrong file type error
image

## Related Issue
Fixes #876 and #875

### CODE REVIEW

**Review by nickbristow — APPROVED** [review]

**Comment by sarahtress** [comment]
@KennethSkylight thanks for the screenshots!

few things:
- the alignment on the left is not all aligned, all elements should have the same vertical alignment on the left. not sure how else to explain that better in writing (perhaps the file input box and buttons below should be shifted to the right to align with the text above it? does that make sense?)
- also this can be addressed in a separate ticket since it's not specifically about the error design, but I just noticed in the blue box, the "this tool is..." text oddly cuts off to be on a second line seemingly for no reason. is it possible to get "site." to be in the first line so it's not unnecessarily 2 lines of text? if that's too tricky here I'll document as a future improvement

**Comment by KennethSkylight** [comment]
@sarahtress Here's the new alignment

image

**Comment by sarahtress** [comment]
@KennethSkylight looks good for the alignment! any thoughts on being able to fix in the blue box "site." being on the next line? I can add that to a future improvement if it's too much for this ticket, just lmk!

**Comment by KennethSkylight** [comment]
@sarahtress oops my bad didn't commit that change.

image

**Pull request merged**
